language: node_js

# Use faster Docker architecture on Travis. (http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)
sudo: false

notifications:
  slack:
    secure: GetOPWIdZf3gnY2twBmVAtmgBwy5xSHHyKc6I6w4s8kXSuOG14cpTrMOkBO2HXT3ApovcwoZ1oYv6r7jbCgRit+OVp259God31kFw3gDsI8OSpmygqCIidx0KcwJpMlez3iF2n8rNoy2WtN4se55X7ZduTJEru4OvoG6I8Vh0tw=

# Run the build twice, once with mongodb 2 and 3
# run for mongo 3 requires mongodb service to pull in all dependencies
matrix:
  include:
  - node_js: "6.5"
    services:
    - mongodb
    before_script:
      - npm install -g grunt-cli
      - mongod --version
  - node_js: "6.5"
    env: MONGODB=3.2.9
    before_script:
      - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1204-${MONGODB}.tgz -O /tmp/mongodb.tgz
      - tar -xvf /tmp/mongodb.tgz
      - mkdir /tmp/data
      - ./mongodb-linux-x86_64-ubuntu1204-${MONGODB}/bin/mongod --version
      - ./mongodb-linux-x86_64-ubuntu1204-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &
      - npm install -g grunt-cli
